### ISSUE TITLE
Develop Architecture

### ISSUE THREAD

**Issue by Chris-Horne-Deloitte** [Alex-Chris-FD/fraud-detection#1]
Meet with team to determine general structure of project

**Comment by Alexanderbeaumier** [comment]
create scope of project
- what will project look like when we are finished
- what services will this project need

**Comment by Alexanderbeaumier** [comment]
Infrastructure: VPC with public/private subnets, Internet Gateway, NAT Gateway, route tables, and security groups.
Data Ingestion: S3 for raw/processed data, Lambda for preprocessing, Kinesis for real-time streaming.
Data Processing: Lambda for preprocessing, RDS (PostgreSQL) for storage, SageMaker for ML model training/deployment.
Monitoring: CloudWatch for performance, CloudTrail for auditing.
Result Storage: S3 for results
